# Uncomment the next line to define a global platform for your project
platform :osx, '10.13'
use_frameworks!

target 'macOSSwiftyExtensionExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'SwiftyExtension', :path => '../'

  # Pods for macOSSwiftyExtensionExample

end
